### ISSUE TITLE
What is this route for in your example?

### ISSUE THREAD

**Issue by duro** [radek/hapi-react-router#1]
https://github.com/radek/hapi-react-router/blob/master/example/server.js#L65-L75

I have been using your module as inspiration for a react-route server I am writing. So far I have been able to achieve the desired functionality by simply implementing the plugin.

However I noticed the above route in the example, and I am wondering if it is needed? And if so, what specifically does it get used for?

**Comment by radek** [comment]
No, it's not needed, I was trying to resolve react routes on hapi server here, not understanding that react-routes are handled in react app and are not 'seen' by server. I cleaned that up.
